# Copyright (c) Microsoft. All rights reserved.
#  Licensed under the MIT license.
name: template-model-training-pipeline
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - hyperopt==0.1
    - mlflow==1.22.0
    - azureml-mlflow==1.39.0
    - azureml-core==1.39.0
    - pandas==1.4.2
    - scikit-learn==1.0.2
    - numpy==1.22.0
    - python-dotenv==0.20.0
    - sklearn
    - scipy
    - pyarrow
    - click
    - protobuf==3.20.0